Repository parquet-go/parquet-go, pull requests merged in 2025-01, with the labels that each got.

#201 validate size of fixed-length values written
  column_buffer.go
  parquet_test.go
Labels: enhancement

#205 Lazy load schema state
  column_buffer.go
  schema.go
Labels: enhancement, performance

#208 docs: Fix MergeRowGroups example
  README.md
Labels: documentation

#214 Revert "fix: change r15 usage so its not clobbered with go plugin buildmode"
  bloom/xxhash/sum64uint_amd64.s
  internal/bytealg/count_amd64.s
Labels: bug

#143 Support TIME logical format struct tags
  schema.go
  schema_test.go
Labels: enhancement

#215 fix issue 199
  bloom/xxhash/sum64uint_amd64.s
  encoding/rle/rle_amd64_test.go
  internal/bytealg/count_amd64.s
Labels: bug

#219 write bloom filters near page index
  writer.go
Labels: enhancement

#203 reader: Add ability to read back Key Value metadata
  reader.go
  reader_test.go
Labels: enhancement

#221 release async pages when seeking
  page.go
  row_group_test.go
Labels: performance

#226 simplify the column index implementation
  column_index.go
  column_index_be.go
  column_index_le.go
Labels: internal

#220 ensure we error instead of silently misconstructing rows when we encounter pages of repeated columns that do not start at the beginnig of a row
  .github/workflows/Dockerfile
  .gitignore
  allocator.go
  buffer_test.go
  column.go
  column_chunk.go
  dedupe.go
  errors.go
  file_test.go
  page.go
  parquet_test.go
  reader_test.go
  row.go
  row_group.go
  row_group_test.go
  testdata/issue206.json
  testdata/issue206.parquet
  testdata/issue368.parquet
Labels: bug

#222 improve async mode
  allocator.go
  buffer.go
  column_chunk.go
  file.go
  file_test.go
  multi_row_group.go
  reader.go
  row.go
  row_group.go
Labels: enhancement

#227 test opening files with optimistic read
  file.go
  file_test.go
Labels: bug

#230 expose more file internals
  bloom.go
  column.go
  column_chunk.go
  column_index.go
  file.go
  file_test.go
  offset_index.go
  reader.go
  writer.go
Labels: enhancement

#229 lazily read async pages
  bloom.go
  column.go
  column_chunk.go
  column_index.go
  file.go
  file_test.go
  offset_index.go
  page.go
  reader.go
  row_group.go
  row_group_test.go
  testdata/issue229.parquet
  writer.go
Labels: enhancement
